### ISSUE TITLE
Rechtliche Ergänzungen

### ISSUE THREAD

**Issue by JonDorean** [pniedermeyer/Webentwicklung-Dashoard#20]
Verweise zum Impressum und Datenschuzterklärung der HTW-Saar
Verweis auf Datenquelle: 
- https://www.govdata.de/dl-de/by-2-0
- https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0

**Comment by JonDorean** [comment]
Link zum HTW-Impressum: https://www.htwsaar.de/htw/impressum

**Comment by CedricSchreiner** [comment]
App Footer mit entsprechenden Links eingefügt

**Comment by notepass** [comment]
Muss hier nicht noch etwas DSGVO kram rein? In richtung datenverarbeitung?

**Comment by JonDorean** [comment]
Wir speichern keine Personenbezogenen Daten. Deswegen kein Problem
