### ISSUE TITLE
Backend Schnittstelle zum ausliefern der Website

### ISSUE THREAD

**Issue by JonDorean** [pniedermeyer/Webentwicklung-Dashoard#22]
Vue Website wird mit Build-Befehl erstellt.

**Comment by CedricSchreiner** [comment]
Webseite kann ausgeliefert werden, muss nur im "Backend/src/Website" Ordner abgelegt werden

**Comment by JonDorean** [comment]
Webseite kann mit `npm run build` gebaut werden. Zu finden ist die dann in `/Frontend/dashboard/dist`
