### ISSUE TITLE
Farbe: Balkendiagramm

### ISSUE THREAD

**Issue by notepass** [pniedermeyer/Webentwicklung-Dashoard#3]
Das Balkendiagramm soll analog zur Karte eingefärbt werden (Selber Algorythmus, selbe Farben, Datenbasis allerdings auf BL Ebene)

**Comment by notepass** [comment]
Umsetzung unter Umständen als gesaxcharte Farbberechnungsfunktion zwischen Baken und Karte

**Comment by JonDorean** [comment]
Balken werden eingefärbt, jedoch auf DE-Ebene und nicht auf BL, damit die Balken analog zur Karte eingefärbt sind.
